/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6Q26EfqfPNQuydumhAEs1S
// Component: vNSUZdpxSWhD
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicInvalidate } from "@plasmicapp/react-web/lib/data-sources";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import LoginButton from "../../LoginButton"; // plasmic-import: sda60oPQ2thQ/component
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdOptionGroup } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdOption } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdProgress } from "@plasmicpkgs/antd5/skinny/registerProgress";
import { AntdSingleSlider } from "@plasmicpkgs/antd5/skinny/registerSlider";
import Statistic from "../../Statistic"; // plasmic-import: XiE-mD4aZZD3/component
import Dialog from "../../Dialog"; // plasmic-import: uwSU6gicCc_e/component
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2";
import { Timer } from "@plasmicpkgs/plasmic-basic-components";
import EmailInput from "../../EmailInput"; // plasmic-import: N6jiyqjMi6tf/component
import { useScreenVariants as useScreenVariantsnnPusS1DHa } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nnPus_s1dHa_/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6Q26EfqfPNQuydumhAEs1S/projectcss
import sty from "./PlasmicCServiceDashboard.module.css"; // plasmic-import: vNSUZdpxSWhD/css
import ChevronDownSvgIcon from "./icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: Bg6ckfv9Qt0z/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: oL00ISW-Qg-T/icon
import logoPng2S9Gcm9LGTbT6 from "./images/logoPng2.png"; // plasmic-import: s9GCM9lGTbT6/picture

createPlasmicElementProxy;

export const PlasmicCServiceDashboard__VariantProps = new Array();

export const PlasmicCServiceDashboard__ArgProps = new Array();

const $$ = {};

function PlasmicCServiceDashboard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "slider.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "dialog.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "emailInput2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnnPusS1DHa()
  });
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"testeDoCarlos"}
        data-plasmic-override={overrides.testeDoCarlos}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.testeDoCarlos
        )}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"topBar"}
          data-plasmic-override={overrides.topBar}
          hasGap={true}
          className={classNames(projectcss.all, sty.topBar)}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ngXf8)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mHutQ)}
            >
              <NavigationBar
                data-plasmic-name={"navigationBar"}
                data-plasmic-override={overrides.navigationBar}
                brand={
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__efwAl
                    )}
                    href={`/corporative-page`}
                    onClick={async event => {
                      const $steps = {};
                      $steps["refreshData"] = true
                        ? (() => {
                            const actionArgs = {
                              queryInvalidation: ["plasmic_refresh_all"]
                            };
                            return (async ({ queryInvalidation }) => {
                              if (!queryInvalidation) {
                                return;
                              }
                              await plasmicInvalidate(queryInvalidation);
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["refreshData"] != null &&
                        typeof $steps["refreshData"] === "object" &&
                        typeof $steps["refreshData"].then === "function"
                      ) {
                        $steps["refreshData"] = await $steps["refreshData"];
                      }
                    }}
                    platform={"react"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2JXdQ)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: logoPng2S9Gcm9LGTbT6,
                        fullWidth: 190,
                        fullHeight: 100,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                }
                className={classNames("__wab_instance", sty.navigationBar)}
                closeButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__tHb0U)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/close.svg"}
                  />
                }
                itemsGap={8}
                menuItems={
                  <React.Fragment>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__nKk8Z
                      )}
                      href={`/company-profile`}
                      platform={"react"}
                    >
                      {"Company\nprofile"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__wVhNu
                      )}
                      href={`/services-dashboard`}
                      platform={"react"}
                    >
                      {"Service\nDashboard"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__wSzrw
                      )}
                      platform={"react"}
                    >
                      {"Market\nTrends"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___15Q6E
                      )}
                      href={`/find-a-affiliate`}
                      platform={"react"}
                    >
                      {"Find a \naffiliate"}
                    </PlasmicLink__>
                  </React.Fragment>
                }
                openButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__eDtGo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    height={``}
                    src={"https://static1.plasmic.app/menu.svg"}
                    width={``}
                  />
                }
                responsiveBreakpoint={768}
              />

              <AntdDropdown
                data-plasmic-name={"account"}
                data-plasmic-override={overrides.account}
                className={classNames("__wab_instance", sty.account)}
                dropdownMenuScopeClassName={sty["account__dropdownMenu"]}
                menuClassName={classNames({ [sty["pcls_p7qz_rVaetlr"]]: true })}
                menuItemClassName={classNames({
                  [sty["pcls_zD__G3rE5Zt_"]]: true
                })}
                menuItems={() => (
                  <React.Fragment>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__tLnx
                      )}
                      key={"menu-item-1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dJbfU
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__ko28I
                      )}
                      key={"menu-item-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xl24Y
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                  </React.Fragment>
                )}
                menuItemsJson={(() => {
                  const __composite = [
                    {
                      type: null,
                      value: "action1",
                      label: null,
                      children: null
                    },
                    {
                      type: null,
                      value: "action2",
                      label: null,
                      onClick: null
                    },
                    { type: "item" }
                  ];

                  __composite["0"]["type"] = "group";
                  __composite["0"]["label"] = "Account";
                  __composite["0"]["children"] = (() => {
                    const __composite = [
                      { type: "item", label: null, onClick: null },
                      { type: "item", label: null, onClick: null },
                      { type: null }
                    ];

                    __composite["0"]["label"] = "Settings & Privacy";
                    __composite["0"]["onClick"] = async info => {
                      const $steps = {};
                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                location.assign(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    __composite["1"]["label"] = "Help";
                    __composite["1"]["onClick"] = async info => {
                      const $steps = {};
                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                location.assign(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    __composite["2"]["type"] = "divider";
                    return __composite;
                  })();
                  __composite["1"]["type"] = "item";
                  __composite["1"]["label"] = "Sign out";
                  __composite["1"]["onClick"] = async info => {
                    const $steps = {};
                    $steps["goToALogin"] = true
                      ? (() => {
                          const actionArgs = { destination: `/a-login` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToALogin"] != null &&
                      typeof $steps["goToALogin"] === "object" &&
                      typeof $steps["goToALogin"].then === "function"
                    ) {
                      $steps["goToALogin"] = await $steps["goToALogin"];
                    }
                  };
                  return __composite;
                })()}
                trigger={"hover"}
                useMenuItemsSlot={false}
              >
                <AntdButton
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  target={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kqtXn)}
                    displayHeight={"30px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"30px"}
                    loading={"lazy"}
                  />
                </AntdButton>
              </AntdDropdown>
            </Stack__>
          </Stack__>
        </Stack__>
        <div
          data-plasmic-name={"countainer1"}
          data-plasmic-override={overrides.countainer1}
          className={classNames(projectcss.all, sty.countainer1)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__uqJOh)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__i55BP
              )}
            >
              {"Period"}
            </div>
            <LoginButton
              className={classNames("__wab_instance", sty.loginButton__kiuEf)}
              color={"softSand"}
              size={"minimal"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fC2Jp
                )}
              >
                {"Custom"}
              </div>
            </LoginButton>
            <LoginButton
              className={classNames("__wab_instance", sty.loginButton__yz1Qe)}
              color={"softSand"}
              size={"minimal"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aZMaN
                )}
              >
                {"Last 7 days"}
              </div>
            </LoginButton>
            <LoginButton
              className={classNames("__wab_instance", sty.loginButton__ahN2H)}
              color={"softSand"}
              size={"minimal"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zVspp
                )}
              >
                {"Last 30 days"}
              </div>
            </LoginButton>
            <LoginButton
              className={classNames("__wab_instance", sty.loginButton__b9Nif)}
              color={"softSand"}
              size={"minimal"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fSgEj
                )}
              >
                {"Last 60 days"}
              </div>
            </LoginButton>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__m6GpU)}>
            <section className={classNames(projectcss.all, sty.section__fdpRk)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ccq6K
                )}
              >
                {"Sales"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__blNxE)}>
              <AntdSelect
                data-plasmic-name={"select"}
                data-plasmic-override={overrides.select}
                allowClear={true}
                className={classNames("__wab_instance", sty.select)}
                defaultOpen={false}
                defaultStylesClassName={classNames(
                  projectcss.root_reset,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  projectcss.plasmic_tokens,
                  plasmic_antd_5_hostless_css.plasmic_tokens,
                  plasmic_plasmic_rich_components_css.plasmic_tokens
                )}
                onChange={async (...eventArgs) => {
                  generateStateOnChangeProp($state, ["select", "value"]).apply(
                    null,
                    eventArgs
                  );
                }}
                options={[
                  { value: "option1", label: "Option 1", type: "option" },
                  { value: "option2", label: "Option 2", type: "option" }
                ]}
                placeholder={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f8RXn
                    )}
                  >
                    {"Solution"}
                  </div>
                }
                popupScopeClassName={sty["select__popup"]}
                suffixIcon={
                  <ChevronDownSvgIcon
                    className={classNames(projectcss.all, sty.svg__cbp1S)}
                    role={"img"}
                  />
                }
                useChildren={true}
                value={generateStateValueProp($state, ["select", "value"])}
              >
                <AntdOptionGroup
                  data-plasmic-name={"optionGroup"}
                  data-plasmic-override={overrides.optionGroup}
                  className={classNames("__wab_instance", sty.optionGroup)}
                  label={null}
                >
                  <AntdOption
                    className={classNames("__wab_instance", sty.option__cyBMz)}
                    value={"option1"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zEfi)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xcl6)}
                        displayHeight={"25px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"25px"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__naHbd
                        )}
                      >
                        {"Option 1"}
                      </div>
                    </div>
                  </AntdOption>
                  <AntdOption
                    className={classNames("__wab_instance", sty.option___4Wp5S)}
                    value={"option1"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__q5Cpz)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__fmxeP)}
                        displayHeight={"25px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"25px"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0EuE4
                        )}
                      >
                        {"Option 1"}
                      </div>
                    </div>
                  </AntdOption>
                </AntdOptionGroup>
              </AntdSelect>
            </section>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__aMp5I)}>
            <div className={classNames(projectcss.all, sty.freeBox__ySulD)}>
              <AntdProgress
                className={classNames("__wab_instance", sty.progress__hX9Ug)}
                size={"default"}
                type={"dashboard"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__d1CJg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___60Bc
                  )}
                >
                  {"Total\nsales"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__zCreo)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qzJhY
                  )}
                >
                  {"27"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nbGxM
                  )}
                >
                  {"/"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mA3Cl
                  )}
                >
                  {"???"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__c3IHm)}>
              <AntdProgress
                className={classNames("__wab_instance", sty.progress___9HbXi)}
                size={"default"}
                type={"dashboard"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__fnK5F)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__seumL
                  )}
                >
                  {"Company\nprofit"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yuUqs)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nqMly
                  )}
                >
                  {"U$$"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Rg4Y
                  )}
                >
                  {"2,405.00"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__f7Wh)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__icw9B
                  )}
                >
                  {"/"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gXjhL
                  )}
                >
                  {"U$$"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fFp9W
                  )}
                >
                  {"2,405.00"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__rJUp)}>
              <AntdProgress
                className={classNames("__wab_instance", sty.progress__tys13)}
                size={"default"}
                type={"dashboard"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__suByj)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ba6Dl
                  )}
                >
                  {"Comission\npaid"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jGgr6)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g95Q2
                  )}
                >
                  {"U$$"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yuAnm
                  )}
                >
                  {"2,405.00"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bEsAh)}>
              <AntdProgress
                className={classNames("__wab_instance", sty.progress__fop0N)}
                size={"default"}
                type={"dashboard"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__yVOkd)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z1Yyf
                  )}
                >
                  {"Total\nAdressable\nMarket"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__zsHoY)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uPu6U
                  )}
                >
                  {"U$$"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8WFOa
                  )}
                >
                  {"2,405.00"}
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__vvREe)}>
            <AntdSingleSlider
              data-plasmic-name={"slider"}
              data-plasmic-override={overrides.slider}
              className={classNames("__wab_instance", sty.slider)}
              marks={[]}
              max={65}
              min={15}
              onChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, ["slider", "value"]).apply(
                  null,
                  eventArgs
                );
              }}
              sliderScopeClassName={sty["slider__slider"]}
              stylableMarks={null}
              tooltipVisible={"unset"}
              value={generateStateValueProp($state, ["slider", "value"])}
            />

            <Statistic
              data-plasmic-name={"statistic"}
              data-plasmic-override={overrides.statistic}
              className={classNames("__wab_instance", sty.statistic)}
              number={
                <div className={classNames(projectcss.all, sty.freeBox__ba8Lp)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sqQoi
                    )}
                  >
                    {"U$"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wGdLj
                    )}
                  >
                    {"3,193"}
                  </div>
                </div>
              }
              unit={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ddlFy
                  )}
                >
                  {"Comission per sale"}
                </div>
              }
            />

            <Dialog
              data-plasmic-name={"dialog"}
              data-plasmic-override={overrides.dialog}
              body={
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p3CPo)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dWHdS
                    )}
                  >
                    {
                      "You have changed your commission, check the viability and change if necessary."
                    }
                  </div>
                </Stack__>
              }
              className={classNames("__wab_instance", sty.dialog)}
              onOpenChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, ["dialog", "open"]).apply(
                  null,
                  eventArgs
                );
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              open={generateStateValueProp($state, ["dialog", "open"])}
              title={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xiqTg
                  )}
                >
                  {"New comission"}
                </div>
              }
              trigger={
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__maPe6
                  )}
                  color={"sand"}
                  size={"minimal"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ijp9U
                    )}
                  >
                    {"Confirm"}
                  </div>
                </LoginButton>
              }
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__rTy)}>
            <SimpleChart
              data-plasmic-name={"chart"}
              data-plasmic-override={overrides.chart}
              className={classNames("__wab_instance", sty.chart)}
              data={[
                { region: "APAC", revenue: 3294, spend: 2675 },
                { region: "EMEA", revenue: 3245, spend: 3895 },
                { region: "LATAM", revenue: 2165, spend: 3498 },
                { region: "AMER", revenue: 3215, spend: 1656 }
              ]}
              fill={false}
              interactive={true}
              labelField={"revenue"}
              type={"bar"}
            />

            <Timer
              data-plasmic-name={"timer"}
              data-plasmic-override={overrides.timer}
              className={classNames("__wab_instance", sty.timer)}
              isRunning={true}
              runWhileEditing={false}
            />
          </div>
        </div>
        <Icon7Icon
          className={classNames(projectcss.all, sty.svg__e3Wfm)}
          role={"img"}
        />

        <div
          data-plasmic-name={"fixedInLoco"}
          data-plasmic-override={overrides.fixedInLoco}
          className={classNames(projectcss.all, sty.fixedInLoco)}
        >
          <div
            data-plasmic-name={"colunsName"}
            data-plasmic-override={overrides.colunsName}
            className={classNames(projectcss.all, sty.colunsName)}
          >
            <section
              className={classNames(projectcss.all, sty.section___1P1Cb)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lr6IW
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___3Tor7)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fF2Xq
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__fBpO)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__szYfM
                )}
              >
                {"ID"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___6O9Me)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gnLxr
                )}
              >
                {"Address"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__jLaWk)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xyVaa
                )}
              >
                {"Estimated time"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___8Nk0V)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sz22U
                )}
              >
                {"Price"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__flTGr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nkTu2
                )}
              >
                {"Status"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingConfirmation"}
            data-plasmic-override={overrides.waitingConfirmation}
            className={classNames(projectcss.all, sty.waitingConfirmation)}
          >
            <section className={classNames(projectcss.all, sty.section__pxGQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Nfv
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__xrVx9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vmZmJ
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ptomh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wuMTl
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___3NlK)}
            />

            <section
              className={classNames(projectcss.all, sty.section__yozud)}
            />

            <section
              className={classNames(projectcss.all, sty.section___2Re4E)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wtdEj
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___955D1
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ijvL)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__qvWFg)}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xmc4I
                  )}
                >
                  {"Confirm"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingLocomotion"}
            data-plasmic-override={overrides.waitingLocomotion}
            className={classNames(projectcss.all, sty.waitingLocomotion)}
          >
            <section
              className={classNames(projectcss.all, sty.section___0QQpM)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Xa0P
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__apzNx)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bhf5C
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ivIzQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__emkX5
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__arM6)}
            />

            <section
              className={classNames(projectcss.all, sty.section__ys07V)}
            />

            <section className={classNames(projectcss.all, sty.section__qEthU)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ij60Y
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vNWhD
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ozInI)}>
              <LoginButton
                className={classNames(
                  "__wab_instance",
                  sty.loginButton___8F3AN
                )}
                color={"green"}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pfJ
                  )}
                >
                  {"On way"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCustomer"}
            data-plasmic-override={overrides.waitingCustomer}
            className={classNames(projectcss.all, sty.waitingCustomer)}
          >
            <section className={classNames(projectcss.all, sty.section__dqz4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6SMEr
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__p3Jkh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oO7PB
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__uMJ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5KRfn
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__vUKnG)}
            />

            <section
              className={classNames(projectcss.all, sty.section__jSmOg)}
            />

            <section
              className={classNames(projectcss.all, sty.section___5P9Uy)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sBl4
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xfzj3
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__sCkN)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aNjIw
                )}
              >
                {"Waiting confirmation"}
              </div>
            </section>
          </div>
        </div>
        <div
          data-plasmic-name={"fixedOnSite"}
          data-plasmic-override={overrides.fixedOnSite}
          className={classNames(projectcss.all, sty.fixedOnSite)}
        >
          <div
            data-plasmic-name={"colunsName2"}
            data-plasmic-override={overrides.colunsName2}
            className={classNames(projectcss.all, sty.colunsName2)}
          >
            <section className={classNames(projectcss.all, sty.section__uHkCw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ez6CA
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__wbfe1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h9MxT
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__fAvz8)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3Ze25
                )}
              >
                {"ID"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__n7PlM)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8E4Sv
                )}
              >
                {"Scheduled"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__gZtC6)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uAcSr
                )}
              >
                {"Price"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___6BMfo)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0RRam
                )}
              >
                {"Status"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingConfirmation3"}
            data-plasmic-override={overrides.waitingConfirmation3}
            className={classNames(projectcss.all, sty.waitingConfirmation3)}
          >
            <section className={classNames(projectcss.all, sty.section__szDld)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mlv8N
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___7I0GP)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qtXcp
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__jttPl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o9U0B
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___3UiwB)}
            />

            <section className={classNames(projectcss.all, sty.section__nMT8)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pYcD3
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___68KwV
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__hdzsf)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__bDug)}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jRbb
                  )}
                >
                  {"Confirm"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCostumer"}
            data-plasmic-override={overrides.waitingCostumer}
            className={classNames(projectcss.all, sty.waitingCostumer)}
          >
            <section className={classNames(projectcss.all, sty.section__uoySj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9E2Dq
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___5MjdC)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qm2NX
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__vMTix)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__otp60
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__wjnKk)}
            />

            <section className={classNames(projectcss.all, sty.section__gd9V)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6Sx2
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fgyPg
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__uxsQz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__co5Qv
                )}
              >
                {"Waiting confirmation"}
              </div>
            </section>
          </div>
        </div>
        <div
          data-plasmic-name={"budgetInLoco"}
          data-plasmic-override={overrides.budgetInLoco}
          className={classNames(projectcss.all, sty.budgetInLoco)}
        >
          <div
            data-plasmic-name={"colunsName3"}
            data-plasmic-override={overrides.colunsName3}
            className={classNames(projectcss.all, sty.colunsName3)}
          >
            <section className={classNames(projectcss.all, sty.section__yTtCr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__izEln
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__qMMtS)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sgca5
                )}
              >
                {"Community"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___6Oy2V)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__v0Rk
                )}
              >
                {"ID"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__hV08C)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7RbK2
                )}
              >
                {"Address"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__membu)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d7Lt6
                )}
              >
                {"Estimated time"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__twFKr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xiHvE
                )}
              >
                {"Price"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__lXKfV)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gTuQy
                )}
              >
                {"Status"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingConfirmation2"}
            data-plasmic-override={overrides.waitingConfirmation2}
            className={classNames(projectcss.all, sty.waitingConfirmation2)}
          >
            <section className={classNames(projectcss.all, sty.section__rhTyT)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___09BOr
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__lOu3A)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oCAgk
                )}
              >
                {"Community"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___8RSo8)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rief6
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__a5YYq)}
            />

            <section
              className={classNames(projectcss.all, sty.section___5NgAl)}
            />

            <section className={classNames(projectcss.all, sty.section__vjY5B)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fqdm0
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o129J
                )}
              >
                {"--"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__zsaeE)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__z2Foa)}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fTckq
                  )}
                >
                  {"Confirm"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingLocomotion2"}
            data-plasmic-override={overrides.waitingLocomotion2}
            className={classNames(projectcss.all, sty.waitingLocomotion2)}
          >
            <section className={classNames(projectcss.all, sty.section__bpJul)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d0SjW
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__saqW)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sa32
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__eKegQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cnlIc
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___7REmp)}
            />

            <section
              className={classNames(projectcss.all, sty.section___5U9Kz)}
            />

            <section className={classNames(projectcss.all, sty.section__uw6Cj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8ZuMr
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2O2Ar
                )}
              >
                {"--"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___1W53W)}
            >
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__dmj53)}
                color={"green"}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__thrJk
                  )}
                >
                  {"On way"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingLocomotion3"}
            data-plasmic-override={overrides.waitingLocomotion3}
            className={classNames(projectcss.all, sty.waitingLocomotion3)}
          >
            <section className={classNames(projectcss.all, sty.section__dlVQi)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tvYy0
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__zHwGs)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6HQFm
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__yXhgh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tyGt3
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__xOihS)}
            />

            <section
              className={classNames(projectcss.all, sty.section___60Rjn)}
            />

            <section className={classNames(projectcss.all, sty.section__l2Q99)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tmFzq
                )}
              >
                {"U$"}
              </div>
              <EmailInput
                data-plasmic-name={"emailInput"}
                data-plasmic-override={overrides.emailInput}
                className={classNames("__wab_instance", sty.emailInput)}
                onChange={async (...eventArgs) => {
                  ((...eventArgs) => {
                    generateStateOnChangeProp($state, ["emailInput", "value"])(
                      (e => e.target?.value).apply(null, eventArgs)
                    );
                  }).apply(null, eventArgs);
                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                string={"Proposal"}
                value={
                  generateStateValueProp($state, ["emailInput", "value"]) ?? ""
                }
              />
            </section>
            <section className={classNames(projectcss.all, sty.section__wvn4E)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__qgGhB)}
                color={"green"}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__txm2M
                  )}
                >
                  {"Send"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCustomer2"}
            data-plasmic-override={overrides.waitingCustomer2}
            className={classNames(projectcss.all, sty.waitingCustomer2)}
          >
            <section
              className={classNames(projectcss.all, sty.section___51Snt)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p0GV
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___0WzhU)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zc5Wq
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__icqew)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__v7JfR
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__zB2WX)}
            />

            <section
              className={classNames(projectcss.all, sty.section__maY53)}
            />

            <section className={classNames(projectcss.all, sty.section__aoEw4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iyOyZ
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eHnq8
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___3WJxk)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wZ7Ab
                )}
              >
                {"Proposal send"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingLocomotion4"}
            data-plasmic-override={overrides.waitingLocomotion4}
            className={classNames(projectcss.all, sty.waitingLocomotion4)}
          >
            <section className={classNames(projectcss.all, sty.section__q2RMc)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__asy8
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__dInFe)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5PDtp
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__oaO5T)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yd3O
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__a4H5M)}
            />

            <section
              className={classNames(projectcss.all, sty.section___6C4Ch)}
            />

            <section className={classNames(projectcss.all, sty.section__u90K9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dFjVb
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3K9ZI
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__qxXwh)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__aSlVl)}
                color={"green"}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rsfKv
                  )}
                >
                  {"On way"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCustomer3"}
            data-plasmic-override={overrides.waitingCustomer3}
            className={classNames(projectcss.all, sty.waitingCustomer3)}
          >
            <section className={classNames(projectcss.all, sty.section__jgFXj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uXoJh
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__dknIw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lajy2
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__hsIjd)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kuBCu
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___0OdFl)}
            />

            <section
              className={classNames(projectcss.all, sty.section__vaja5)}
            />

            <section className={classNames(projectcss.all, sty.section__nRrh1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jHeuG
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gTcHz
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__mcn9S)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y6LPw
                )}
              >
                {"Waiting confirmation"}
              </div>
            </section>
          </div>
        </div>
        <div
          data-plasmic-name={"budgetOnSite"}
          data-plasmic-override={overrides.budgetOnSite}
          className={classNames(projectcss.all, sty.budgetOnSite)}
        >
          <div
            data-plasmic-name={"colunsName4"}
            data-plasmic-override={overrides.colunsName4}
            className={classNames(projectcss.all, sty.colunsName4)}
          >
            <section className={classNames(projectcss.all, sty.section__aLhGo)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7Pgev
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__teOwg)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ppHok
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__rmiH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kGsNv
                )}
              >
                {"ID"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__tzDC)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eYgDt
                )}
              >
                {"Scheduled"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__nDgtp)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pf0Gt
                )}
              >
                {"Price"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___7OPbt)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mRQtf
                )}
              >
                {"Status"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingConfirmation4"}
            data-plasmic-override={overrides.waitingConfirmation4}
            className={classNames(projectcss.all, sty.waitingConfirmation4)}
          >
            <section className={classNames(projectcss.all, sty.section__gmRuV)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vbXq
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__klG0L)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cc2Sc
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ngG88)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xHNiL
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__sYiu)}
            />

            <section className={classNames(projectcss.all, sty.section__mAvcz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wrUos
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__giMzk
                )}
              >
                {"--"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__oWz4Z)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__bBtkI)}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vbSze
                  )}
                >
                  {"Confirm"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingLocomotion5"}
            data-plasmic-override={overrides.waitingLocomotion5}
            className={classNames(projectcss.all, sty.waitingLocomotion5)}
          >
            <section className={classNames(projectcss.all, sty.section__j3PT)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vcl6M
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__qtOwh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jxPqd
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__om7Xg)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mwfs3
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__tStqr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uYrt3
                )}
              >
                {"--"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__dFmrf)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dabYw
                )}
              >
                {"U$"}
              </div>
              <EmailInput
                data-plasmic-name={"emailInput2"}
                data-plasmic-override={overrides.emailInput2}
                className={classNames("__wab_instance", sty.emailInput2)}
                onChange={async (...eventArgs) => {
                  ((...eventArgs) => {
                    generateStateOnChangeProp($state, ["emailInput2", "value"])(
                      (e => e.target?.value).apply(null, eventArgs)
                    );
                  }).apply(null, eventArgs);
                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                string={"Proposal"}
                value={
                  generateStateValueProp($state, ["emailInput2", "value"]) ?? ""
                }
              />
            </section>
            <section className={classNames(projectcss.all, sty.section__lue6Z)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__iybUx)}
                color={"green"}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zZrsZ
                  )}
                >
                  {"Send"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCostumer2"}
            data-plasmic-override={overrides.waitingCostumer2}
            className={classNames(projectcss.all, sty.waitingCostumer2)}
          >
            <section className={classNames(projectcss.all, sty.section__bpPj9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4U4Gg
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__jBwli)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nAQbG
                )}
              >
                {"Community"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___6Fp3X)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Dv4O
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__uwtbx)}
            />

            <section className={classNames(projectcss.all, sty.section__fxVgl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__in24
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1CNr2
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__aF4YV)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7WDoi
                )}
              >
                {"Proposal send"}
              </div>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingConfirmation5"}
            data-plasmic-override={overrides.waitingConfirmation5}
            className={classNames(projectcss.all, sty.waitingConfirmation5)}
          >
            <section className={classNames(projectcss.all, sty.section__xcWUe)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xFubv
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__x5Ewl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__w74De
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__nuZ6)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rteOu
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__zflX4)}
            />

            <section
              className={classNames(projectcss.all, sty.section___32FCc)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9D2JD
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sEqKf
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__ife3S)}>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__tiwC6)}
                size={"minimal"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8HR2H
                  )}
                >
                  {"Confirm"}
                </div>
              </LoginButton>
            </section>
          </div>
          <div
            data-plasmic-name={"waitingCostumer3"}
            data-plasmic-override={overrides.waitingCostumer3}
            className={classNames(projectcss.all, sty.waitingCostumer3)}
          >
            <section className={classNames(projectcss.all, sty.section__kh1L1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qouXm
                )}
              >
                {"Solution"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__hTMt)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eaDCv
                )}
              >
                {"Community"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__kk0Da)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___67Zhd
                )}
              >
                {"#000000000"}
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section__iFipa)}
            />

            <section className={classNames(projectcss.all, sty.section__oIphi)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xuzXh
                )}
              >
                {"U$"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__m3VHh
                )}
              >
                {"2,405.00"}
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__dnbef)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dmFrf
                )}
              >
                {"Waiting confirmation"}
              </div>
            </section>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  testeDoCarlos: [
    "testeDoCarlos",
    "topBar",
    "navigationBar",
    "account",
    "button",
    "countainer1",
    "select",
    "optionGroup",
    "slider",
    "statistic",
    "dialog",
    "chart",
    "timer",
    "fixedInLoco",
    "colunsName",
    "waitingConfirmation",
    "waitingLocomotion",
    "waitingCustomer",
    "fixedOnSite",
    "colunsName2",
    "waitingConfirmation3",
    "waitingCostumer",
    "budgetInLoco",
    "colunsName3",
    "waitingConfirmation2",
    "waitingLocomotion2",
    "waitingLocomotion3",
    "emailInput",
    "waitingCustomer2",
    "waitingLocomotion4",
    "waitingCustomer3",
    "budgetOnSite",
    "colunsName4",
    "waitingConfirmation4",
    "waitingLocomotion5",
    "emailInput2",
    "waitingCostumer2",
    "waitingConfirmation5",
    "waitingCostumer3"
  ],

  topBar: ["topBar", "navigationBar", "account", "button"],
  navigationBar: ["navigationBar"],
  account: ["account", "button"],
  button: ["button"],
  countainer1: [
    "countainer1",
    "select",
    "optionGroup",
    "slider",
    "statistic",
    "dialog",
    "chart",
    "timer"
  ],

  select: ["select", "optionGroup"],
  optionGroup: ["optionGroup"],
  slider: ["slider"],
  statistic: ["statistic"],
  dialog: ["dialog"],
  chart: ["chart"],
  timer: ["timer"],
  fixedInLoco: [
    "fixedInLoco",
    "colunsName",
    "waitingConfirmation",
    "waitingLocomotion",
    "waitingCustomer"
  ],

  colunsName: ["colunsName"],
  waitingConfirmation: ["waitingConfirmation"],
  waitingLocomotion: ["waitingLocomotion"],
  waitingCustomer: ["waitingCustomer"],
  fixedOnSite: [
    "fixedOnSite",
    "colunsName2",
    "waitingConfirmation3",
    "waitingCostumer"
  ],

  colunsName2: ["colunsName2"],
  waitingConfirmation3: ["waitingConfirmation3"],
  waitingCostumer: ["waitingCostumer"],
  budgetInLoco: [
    "budgetInLoco",
    "colunsName3",
    "waitingConfirmation2",
    "waitingLocomotion2",
    "waitingLocomotion3",
    "emailInput",
    "waitingCustomer2",
    "waitingLocomotion4",
    "waitingCustomer3"
  ],

  colunsName3: ["colunsName3"],
  waitingConfirmation2: ["waitingConfirmation2"],
  waitingLocomotion2: ["waitingLocomotion2"],
  waitingLocomotion3: ["waitingLocomotion3", "emailInput"],
  emailInput: ["emailInput"],
  waitingCustomer2: ["waitingCustomer2"],
  waitingLocomotion4: ["waitingLocomotion4"],
  waitingCustomer3: ["waitingCustomer3"],
  budgetOnSite: [
    "budgetOnSite",
    "colunsName4",
    "waitingConfirmation4",
    "waitingLocomotion5",
    "emailInput2",
    "waitingCostumer2",
    "waitingConfirmation5",
    "waitingCostumer3"
  ],

  colunsName4: ["colunsName4"],
  waitingConfirmation4: ["waitingConfirmation4"],
  waitingLocomotion5: ["waitingLocomotion5", "emailInput2"],
  emailInput2: ["emailInput2"],
  waitingCostumer2: ["waitingCostumer2"],
  waitingConfirmation5: ["waitingConfirmation5"],
  waitingCostumer3: ["waitingCostumer3"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCServiceDashboard__ArgProps,
          internalVariantPropNames: PlasmicCServiceDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCServiceDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "testeDoCarlos") {
    func.displayName = "PlasmicCServiceDashboard";
  } else {
    func.displayName = `PlasmicCServiceDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicCServiceDashboard = Object.assign(
  // Top-level PlasmicCServiceDashboard renders the root element
  makeNodeComponent("testeDoCarlos"),
  {
    // Helper components rendering sub-elements
    topBar: makeNodeComponent("topBar"),
    navigationBar: makeNodeComponent("navigationBar"),
    account: makeNodeComponent("account"),
    button: makeNodeComponent("button"),
    countainer1: makeNodeComponent("countainer1"),
    select: makeNodeComponent("select"),
    optionGroup: makeNodeComponent("optionGroup"),
    slider: makeNodeComponent("slider"),
    statistic: makeNodeComponent("statistic"),
    dialog: makeNodeComponent("dialog"),
    chart: makeNodeComponent("chart"),
    timer: makeNodeComponent("timer"),
    fixedInLoco: makeNodeComponent("fixedInLoco"),
    colunsName: makeNodeComponent("colunsName"),
    waitingConfirmation: makeNodeComponent("waitingConfirmation"),
    waitingLocomotion: makeNodeComponent("waitingLocomotion"),
    waitingCustomer: makeNodeComponent("waitingCustomer"),
    fixedOnSite: makeNodeComponent("fixedOnSite"),
    colunsName2: makeNodeComponent("colunsName2"),
    waitingConfirmation3: makeNodeComponent("waitingConfirmation3"),
    waitingCostumer: makeNodeComponent("waitingCostumer"),
    budgetInLoco: makeNodeComponent("budgetInLoco"),
    colunsName3: makeNodeComponent("colunsName3"),
    waitingConfirmation2: makeNodeComponent("waitingConfirmation2"),
    waitingLocomotion2: makeNodeComponent("waitingLocomotion2"),
    waitingLocomotion3: makeNodeComponent("waitingLocomotion3"),
    emailInput: makeNodeComponent("emailInput"),
    waitingCustomer2: makeNodeComponent("waitingCustomer2"),
    waitingLocomotion4: makeNodeComponent("waitingLocomotion4"),
    waitingCustomer3: makeNodeComponent("waitingCustomer3"),
    budgetOnSite: makeNodeComponent("budgetOnSite"),
    colunsName4: makeNodeComponent("colunsName4"),
    waitingConfirmation4: makeNodeComponent("waitingConfirmation4"),
    waitingLocomotion5: makeNodeComponent("waitingLocomotion5"),
    emailInput2: makeNodeComponent("emailInput2"),
    waitingCostumer2: makeNodeComponent("waitingCostumer2"),
    waitingConfirmation5: makeNodeComponent("waitingConfirmation5"),
    waitingCostumer3: makeNodeComponent("waitingCostumer3"),
    // Metadata about props expected for PlasmicCServiceDashboard
    internalVariantProps: PlasmicCServiceDashboard__VariantProps,
    internalArgProps: PlasmicCServiceDashboard__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Services dashboard",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCServiceDashboard;
/* prettier-ignore-end */
