/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6Q26EfqfPNQuydumhAEs1S
// Component: 6oesRwYEnbX0
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LoginButton from "../../LoginButton"; // plasmic-import: sda60oPQ2thQ/component
import ListingListBox from "../../ListingListBox"; // plasmic-import: nruvBxNcyS4U/component
import Button4 from "../../Button4"; // plasmic-import: Yuxa95wIKkuN/component
import FooterSection from "../../FooterSection"; // plasmic-import: V9WWasIOlC1n/component
import { useScreenVariants as useScreenVariantsnnPusS1DHa } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nnPus_s1dHa_/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6Q26EfqfPNQuydumhAEs1S/projectcss
import sty from "./PlasmicCLandingpage.module.css"; // plasmic-import: 6oesRwYEnbX0/css
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: -FEsXBzHdryM/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: -PiAVLOujHOd/icon
import LossChartSvgrepoComSvgIcon from "./icons/PlasmicIcon__LossChartSvgrepoComSvg"; // plasmic-import: EtNnTSWPJqg9/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: RMhTIsfKIcza/icon
import ReportSvgrepoComSvgIcon from "./icons/PlasmicIcon__ReportSvgrepoComSvg"; // plasmic-import: a-8qUDv5D2bw/icon
import MoneySvgrepoComSvgIcon from "./icons/PlasmicIcon__MoneySvgrepoComSvg"; // plasmic-import: S5T9okuTEHS1/icon
import TrophySportsAndCompetitionSvgrepoComSvgIcon from "./icons/PlasmicIcon__TrophySportsAndCompetitionSvgrepoComSvg"; // plasmic-import: 3XJHabKZubow/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: kQt1gvqXyKxy/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 71nXQxWpb_nm/icon
import logoPng3MTwlwyjv80Eq from "./images/logoPng3.png"; // plasmic-import: mTWLWYJV80Eq/picture
import pexelsAmardeepSingh6327356829771JpgLemnrzqJlcSw from "./images/pexelsAmardeepSingh6327356829771Jpg.jpg"; // plasmic-import: LEMNRZQJlcSw/picture
import house14075621920JpgFjSTr5DagMxT from "./images/house14075621920Jpg.jpg"; // plasmic-import: FjSTr5DAGMxT/picture
import pexelsNicolaBarts7927581JpgErNseZIbaXy from "./images/pexelsNicolaBarts7927581Jpg.jpg"; // plasmic-import: -ErNseZIbaXY/picture
import pexelsPixabay34514JpgHOwExlvSiNx from "./images/pexelsPixabay34514Jpg.jpg"; // plasmic-import: hOW_exlvSiNX/picture
import pexelsShkrabaanthony5816299JpgNlRe6RZ1SxEk from "./images/pexelsShkrabaanthony5816299Jpg.jpg"; // plasmic-import: nlRe6rZ1SXEk/picture

createPlasmicElementProxy;

export const PlasmicCLandingpage__VariantProps = new Array();

export const PlasmicCLandingpage__ArgProps = new Array();

const $$ = {};

function PlasmicCLandingpage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnnPusS1DHa()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"cabecalho"}
            data-plasmic-override={overrides.cabecalho}
            className={classNames(projectcss.all, sty.cabecalho)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__icCNt)}>
              <div className={classNames(projectcss.all, sty.freeBox__zbFz)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___0GtXu)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bDhtd)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"500px"}
                    loading={"lazy"}
                    src={{
                      src: logoPng3MTwlwyjv80Eq,
                      fullWidth: 2888,
                      fullHeight: 392,
                      aspectRatio: undefined
                    }}
                  />

                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"COMPANIES: GROW WITHOUT SPENDING ON MARKETING"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zwv79
                    )}
                  >
                    {"Risk-Free Marketing: Agencies Invest in your success!"}
                  </div>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__pQr2B
                    )}
                    platform={"react"}
                  >
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__u7Zg)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uM7X
                      )}
                    >
                      {"Get in touch"}
                    </div>
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__bQdK)}
                      role={"img"}
                    />
                  </Stack__>
                  <LoginButton
                    className={classNames(
                      "__wab_instance",
                      sty.loginButton__kkmop
                    )}
                    link={`/c-landing-page-contact`}
                    shape={"rounded"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nMchn
                      )}
                    >
                      {"Get in wait list"}
                    </div>
                  </LoginButton>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ryIqF)}>
                <div className={classNames(projectcss.all, sty.freeBox__s4VU)}>
                  <ChevronDown2Icon
                    className={classNames(projectcss.all, sty.svg__oBjS5)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yU6Ma)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__xoMeg)}
              displayHeight={"400px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: pexelsAmardeepSingh6327356829771JpgLemnrzqJlcSw,
                fullWidth: 4032,
                fullHeight: 3024,
                aspectRatio: undefined
              }}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"subtituloEProblema"}
            data-plasmic-override={overrides.subtituloEProblema}
            hasGap={true}
            className={classNames(projectcss.all, sty.subtituloEProblema)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__myJd8)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"subtitulo"}
                data-plasmic-override={overrides.subtitulo}
                hasGap={true}
                className={classNames(projectcss.all, sty.subtitulo)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8G8O9
                  )}
                >
                  {"WHAT IS EZ MARKETING?"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__tzs79
                  )}
                >
                  {
                    "EZ MARKETING CONNECTS COMPANIES TO MARKETING AGENCIES THAT INVEST IN THEIR GROWTH"
                  }
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tGVfO
                  )}
                >
                  {
                    "EZ Marketing is a disruptive platform that aims to transform the digital marketing landscape. Our goal is to centralize, measure and optimize marketing investments, meeting the needs of companies and professionals who face historical challenges in the sector. The platform guarantees secure payment for the service"
                  }
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"problem"}
                data-plasmic-override={overrides.problem}
                hasGap={true}
                className={classNames(projectcss.all, sty.problem)}
              >
                <div className={classNames(projectcss.all, sty.column__zhpp)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ap79S)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: house14075621920JpgFjSTr5DagMxT,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__yk1Kg)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__tto49)}
                  >
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Real state agent heading"
                        : "THE PROBLEM:"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vRtXv
                      )}
                    >
                      {
                        "Marketing is Increasingly Expensive, the digital marketing market needs a solution that brings transparency, reliability and efficiency to all parties involved."
                      }
                    </div>
                  </Stack__>
                  <div className={classNames(projectcss.all, sty.freeBox__a6V)}>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___92Xg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zvkyE
                        )}
                      >
                        <LossChartSvgrepoComSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___9QDa8
                          )}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sp9Ll
                        )}
                      >
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__gu0WO)}
                          role={"img"}
                        />
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gb20X
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oBc6
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__yCsJd
                            )}
                          >
                            {
                              "Companies spend thousands on ads with no guarantee of return."
                            }
                          </h5>
                        </div>
                      </Stack__>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sbBzl)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ncGmj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__r6RkE
                        )}
                      >
                        <ReportSvgrepoComSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8Wbhb
                          )}
                          role={"img"}
                        />
                      </div>
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eMZf9
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sjl6R
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4Umg
                        )}
                      >
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___5Sq0
                          )}
                        >
                          {
                            "Agencies with unrealistic promises just to get a contract."
                          }
                        </h5>
                      </Stack__>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7Cq0N)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__yXqVa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4HMOi
                        )}
                      >
                        <MoneySvgrepoComSvgIcon
                          className={classNames(projectcss.all, sty.svg__h2HAn)}
                          role={"img"}
                        />
                      </div>
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___1OP5
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__z7PE
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__b6GPr
                        )}
                      >
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__k4LSy
                          )}
                        >
                          {
                            "Small and medium-sized companies don't have the budget for large campaigns."
                          }
                        </h5>
                      </Stack__>
                    </Stack__>
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"solucao"}
            data-plasmic-override={overrides.solucao}
            hasGap={true}
            className={classNames(projectcss.all, sty.solucao)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xm40X)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___3KiQz
                  )}
                >
                  {"THE SOLUTION:\nAGENCIES INVEST IN YOU"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kp6W
                  )}
                >
                  {
                    "By combining market analysis tools, competitor differentiation, price dynamics management and continuous feedback, in addition to the best portfolio made to showcase the work of marketing agencies, the platform positions itself as the first system that offers a unified and detailed view of each company's performance in relation to its potential."
                  }
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"vantagens"}
                data-plasmic-override={overrides.vantagens}
                hasGap={true}
                className={classNames(projectcss.all, sty.vantagens)}
              >
                <div className={classNames(projectcss.all, sty.column__fgPy6)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__j6Zp0
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8EJ6
                          )}
                        >
                          <MoneySvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zsFXv
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__lHl21
                          )}
                        >
                          {"No financial risk"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pQdAj
                          )}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__o9FG3
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hXmki
                              )}
                            >
                              {"Agencies invest like VC investors."}
                            </div>
                          </Stack__>
                        </Stack__>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__q24Vw)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: pexelsNicolaBarts7927581JpgErNseZIbaXy,
                        fullWidth: 6000,
                        fullHeight: 4000,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__cyZt1)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox___0ExmX
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zs9Kk
                          )}
                        >
                          <TrophySportsAndCompetitionSvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kOitA
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__mzToi
                          )}
                        >
                          {"Competition in your favor"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___4SJsZ
                          )}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__arBbX
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__l0XH
                              )}
                            >
                              {"Different agencies compete for your growth."}
                            </div>
                          </Stack__>
                        </Stack__>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__oIy3G)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: pexelsPixabay34514JpgHOwExlvSiNx,
                        fullWidth: 7197,
                        fullHeight: 4803,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column___51Akj)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__aLubW
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y7YUu
                          )}
                        >
                          <ReportSvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tadk3
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__lAcKy
                          )}
                        >
                          {"Full monitoring"}
                        </h4>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kAsQm
                          )}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dDltN
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5W42K
                              )}
                            >
                              {
                                "From CONVERSION TO PAYMENT CONFIRMATION, all within the platform."
                              }
                            </div>
                          </Stack__>
                        </Stack__>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qvuBk)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: pexelsShkrabaanthony5816299JpgNlRe6RZ1SxEk,
                        fullWidth: 4000,
                        fullHeight: 6000,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"provaSocial"}
            data-plasmic-override={overrides.provaSocial}
            hasGap={true}
            className={classNames(projectcss.all, sty.provaSocial)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__f25YT)}>
              <div className={classNames(projectcss.all, sty.freeBox__f2Y5C)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"left2"}
                  data-plasmic-override={overrides.left2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.left2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zFi7V
                    )}
                  >
                    {"Social proof"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__fzJl8
                    )}
                  >
                    {
                      '"If you\'re not an expert, outsource it to those who are."'
                    }
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gOpyn
                    )}
                  >
                    {"-Gary Vaynerchuk"}
                  </div>
                  <LoginButton
                    className={classNames(
                      "__wab_instance",
                      sty.loginButton__vlxdd
                    )}
                    link={`/c-landing-page-contact`}
                    shape={"rounded"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mtt70
                      )}
                    >
                      {"Get in wait list"}
                    </div>
                  </LoginButton>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__j5NA
                    )}
                    platform={"react"}
                  >
                    {false ? (
                      <Icon13Icon
                        className={classNames(projectcss.all, sty.svg___9QLkY)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xjwxX
                      )}
                    >
                      {"Connect"}
                    </div>
                    {false ? (
                      <Icon13Icon
                        className={classNames(projectcss.all, sty.svg__nFbX)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__aJujl)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__g7ZAu)} />
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bsbqF)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xacw1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mlrkE
                  )}
                >
                  {"Let's get going"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___9PlJx
                  )}
                >
                  {"Secure Your Place on the Waiting List!"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uuWLv
                  )}
                >
                  {
                    "Be one of the first companies to access this revolution in digital marketing.\r"
                  }
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__t01Ce)}
              >
                <Button4
                  data-plasmic-name={"button4"}
                  data-plasmic-override={overrides.button4}
                  className={classNames("__wab_instance", sty.button4)}
                  color={"neutral"}
                  end={
                    <Icon15Icon
                      className={classNames(projectcss.all, sty.svg__iU3Qo)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uBeWn
                      )}
                    >
                      {"Submit now"}
                    </div>
                  }
                  linkTo={`/c-landing-page-contact`}
                  size={"large"}
                  start={
                    <CircleIcon
                      className={classNames(projectcss.all, sty.svg__eZQvR)}
                      role={"img"}
                    />
                  }
                />

                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__izyQh
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Learn more..."}
                </PlasmicLink__>
              </Stack__>
            </Stack__>
          </Stack__>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "cabecalho",
    "h1",
    "subtituloEProblema",
    "subtitulo",
    "problem",
    "h3",
    "solucao",
    "foreground2",
    "vantagens",
    "provaSocial",
    "left2",
    "button4",
    "footerSection"
  ],

  cabecalho: ["cabecalho", "h1"],
  h1: ["h1"],
  subtituloEProblema: ["subtituloEProblema", "subtitulo", "problem", "h3"],
  subtitulo: ["subtitulo"],
  problem: ["problem", "h3"],
  h3: ["h3"],
  solucao: ["solucao", "foreground2", "vantagens"],
  foreground2: ["foreground2"],
  vantagens: ["vantagens"],
  provaSocial: ["provaSocial", "left2"],
  left2: ["left2"],
  button4: ["button4"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCLandingpage__ArgProps,
          internalVariantPropNames: PlasmicCLandingpage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCLandingpage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCLandingpage";
  } else {
    func.displayName = `PlasmicCLandingpage.${nodeName}`;
  }
  return func;
}

export const PlasmicCLandingpage = Object.assign(
  // Top-level PlasmicCLandingpage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cabecalho: makeNodeComponent("cabecalho"),
    h1: makeNodeComponent("h1"),
    subtituloEProblema: makeNodeComponent("subtituloEProblema"),
    subtitulo: makeNodeComponent("subtitulo"),
    problem: makeNodeComponent("problem"),
    h3: makeNodeComponent("h3"),
    solucao: makeNodeComponent("solucao"),
    foreground2: makeNodeComponent("foreground2"),
    vantagens: makeNodeComponent("vantagens"),
    provaSocial: makeNodeComponent("provaSocial"),
    left2: makeNodeComponent("left2"),
    button4: makeNodeComponent("button4"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicCLandingpage
    internalVariantProps: PlasmicCLandingpage__VariantProps,
    internalArgProps: PlasmicCLandingpage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCLandingpage;
/* prettier-ignore-end */
